### ISSUE TITLE
First byte of 512 byte config area is a checksum

### ISSUE THREAD

**Issue by dhmsjs** [amper128/mtc_drivers#1]
Thanks for adding the structure of the 512 byte config block to mtc-shared.h.  That is very helpful.  Keep up the good work!

The very first byte of that block is a simple additive checksum over the MCU ID string (for instance "MTCB-KLD2").  The MCU code uses this byte to determine if the current 512 byte config block in external memory is valid or not. 

For MCU version KLD2v2.77 it adds the character values of "MTCB-KLD2" (the string is created with a call to sprintf() and stored at X02AB) and saves that sum at external memory X0012.  When the MCU code wants to know whether or not it can trust the 512 byte config block stored at external memory X02E5, it compares the first byte at X02E5 to the value stored at X0012.  If they match then it assumes the entire block is ok.  If they do not match then it loads a default block of hard coded values into EEPROM and also writes this default config block to the 512 bytes at X02E5.  

There are also two commands to transfer this 512 byte config block to and from the ARM processor.  Command 0x15FF sends the 512 byte block at X02E5 to the ARM.  Command 0x95FE reads the 512 byte block from ARM, writes it to X02E5 and also saves it to EEPROM.

**Comment by amper128** [comment]
Thank you for your help!
